import React from "react";
import {
  Lightbulb,
  Users,
  Briefcase,
  Banknote,
  ScrollText,
  FlaskConical,
} from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

const stats = [
  {
    icon: Lightbulb,
    title: "Total Startups",
    value: "120+",
    desc: "Incubated & accelerated through PRISM-supported centers.",
    detail:
      "Startups that have received incubation, acceleration, or technical mentoring support through PRISM-enabled TOCIC and partner institutions.",
    color: "from-amber-200 to-yellow-400",
  },
  {
    icon: Banknote,
    title: "Funds Raised",
    value: "₹50 Cr",
    desc: "Seed & external funding mobilized.",
    detail:
      "Approximate cumulative seed, grant, and external funding mobilized by PRISM-supported innovators and startups.",
    color: "from-emerald-200 to-green-400",
  },
  {
    icon: ScrollText,
    title: "Patents Filed",
    value: "45",
    desc: "IPRs generated by innovators.",
    detail:
      "Patent applications and other IPRs filed as outcomes of PRISM-supported projects across Phase I and Phase II.",
    color: "from-purple-200 to-violet-400",
  },
  {
    icon: Users,
    title: "Mentors",
    value: "80+",
    desc: "Domain & industry experts.",
    detail:
      "Practitioners, industry leaders, and faculty mentors engaged across TOCIC centers to guide PRISM innovators.",
    color: "from-blue-200 to-indigo-400",
  },
  {
    icon: Briefcase,
    title: "Jobs Created",
    value: "1,500+",
    desc: "Direct employment opportunities.",
    detail:
      "Estimated direct jobs created through ventures, startups, and technology transfer activities supported under PRISM.",
    color: "from-orange-200 to-red-400",
  },
  {
    icon: FlaskConical,
    title: "Labs Support",
    value: "12",
    desc: "R&D facilities with access.",
    detail:
      "Partner labs and R&D facilities providing testing, prototyping, and validation support to PRISM innovators.",
    color: "from-cyan-200 to-sky-400",
  },
];

export default function InnovationStats() {
  return (
    <section className=" backdrop-blur-2xl py-10 px-4">
      <div className="mx-auto max-w-[1400px]">
        {/* Header */}
        <div className="mb-8 flex flex-col items-center justify-center text-center">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">
            Innovation Impact
          </h2>
          <p className="text-sm text-muted-foreground">
            Key metrics showcasing PRISM ecosystem growth
          </p>
        </div>

        {/* Grid: 2 rows × 3 cols on desktop, responsive below */}
        <div className="grid grid-cols-2 gap-4 md:grid-cols-3 max-w-7xl mx-auto lg:grid-cols-3 lg:grid-rows-2">
          {stats.map((stat, index) => (
            <Dialog key={index}>
              <DialogTrigger asChild>
                <button
                  type="button"
                  className="group relative h-full w-full text-left"
                >
                  {/* Hover glow */}
                  <div
                    className={`pointer-events-none absolute inset-0 -z-10 rounded-xl bg-gradient-to-br ${stat.color} opacity-0 blur-xl transition-opacity duration-500 group-hover:opacity-40 `}
                  />

                  <div className="h-full rounded-xl border border-border bg-background/90 shadow-sm transition-transform duration-200 group-hover:-translate-y-1 group-hover:shadow-md">
                    <CardHeader className="space-y-0 p-4 pb-2 text-center ">
                      <div className="mb-2 flex items-center justify-center">
                        <div
                          className={`
                            inline-flex items-center justify-center
                            rounded-lg bg-gradient-to-tl ${stat.color}
                            p-2.5 shadow-sm
                          `}
                        >
                          <stat.icon className="h-5 w-5 text-slate-900/80" />
                        </div>
                      </div>

                      <div className="text-2xl font-bold text-foreground">
                        {stat.value}
                      </div>

                      <CardTitle className="mt-1 text-sm font-medium text-muted-foreground">
                        {stat.title}
                      </CardTitle>
                    </CardHeader>

                    <CardContent className="p-4 pt-0 text-center">
                      <p className="text-xs leading-tight text-muted-foreground">
                        {stat.desc}
                      </p>
                    </CardContent>
                  </div>
                </button>
              </DialogTrigger>

              {/* Popup with more detail */}
              <DialogContent className="max-w-md">
                <DialogHeader>
                  <DialogTitle>{stat.title}</DialogTitle>
                  <DialogDescription>{stat.detail}</DialogDescription>
                </DialogHeader>
              </DialogContent>
            </Dialog>
          ))}
        </div>
      </div>
    </section>
  );
}
